[package]
name = "goni-router"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
goni-types = { path = "../goni-types" }
serde = { workspace = true }
serde_yaml = { workspace = true }
anyhow = "1"
