[package]
name = "goni-cap"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
cap-std = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
