[package]
name = "goni-context"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
goni-types = { path = "../goni-types" }
arrow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
